## ArgoCD configuration
## Ref: https://github.com/argoproj/argo-cd
##
## Server
server:
  ingress:
    enabled: true
  dex:
    enabled: false
  extraArgs:
    - --insecure
  installCRDs: false
  configEnabled: true
  config:
    repositories: |
      - name: argo-helm
        type: helm
        url: https://argoproj.github.io/argo-helm
      - type: helm
        name: stable
        url: https://charts.helm.sh/stable
  additionalProjects: 
  - name: argo
    namespace: argo
    additionalLabels: {}
    additionalAnnotations: {}
    description: Argos Related Applications
    sourceRepos:
    - '*'
    destinations:
    - namespace: argo
      server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    orphanedResources:
      warn: false
  additionalApplications: 
    - name: dev 
      namespace: argo
      destination:
        namespace: argo
        server: https://kubernetes.default.svc
      project: argo
      source:
        path: apps 
        repoURL: https://github.com/JoaoRufino/argocd.git
        targetRevision: HEAD
        helm:
          valueFiles:
          - values.yaml
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true

