apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd.yaml
  namespace: argo 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo 
  project: argo 
  source:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
