apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoworkflows
  namespace: argo 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo 
  project: argo 
  source:
    helm:
      valueFiles:
        - values-workflows.yaml
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.2.5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
