apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoworkflows
  namespace: argo 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo 
  project: argo 
  source:
    helm:
      valueFiles:
        - values.yaml
    path: cicd/charts/argo-workflows
    repoURL: https://github.com/JoaoRufino/cicd.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
