apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
spec:
  project: argo 
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 0.2.5
    helm:
      valueFiles:
        - values.yaml
    chart: argo-workflows
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

