apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoevents
  namespace: argo 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  project: argo 
  source:
    path: charts/argo-events
    repoURL: https://github.com/joaorufino/cicd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true   
